name: Build and Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 7.6.1
          arguments: build


  deploy:
    needs: build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node 12
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
